name: ECDataKit CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'ecdk/**'
      - '.github/workflows/ecdk-ci.yaml'

env:
  WORKING_DIRECTORY: ecdk

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ecdk-ci-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m pytest

