name: Solver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'solver/**'
      - '.github/workflows/solver_ci.yaml'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: solver
jobs:
  build-run:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-build-run-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --release
      - name: Run JSSP example on mock data
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo run --release -- --input-file data/instances/mock_instances/test01.txt --output-dir output

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --release
      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo test --release

  code-format:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-code-format-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Code check with cargo fmt
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-clippy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Code check with clippy
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo clippy

