name: Solver CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "development", "@*/*" ]
    paths:
      - 'solver/**'
      - '.github/workflows/run-jssp-solver.yaml'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: solver
jobs:
  build_run:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --release
      - name: Run JSSP example on mock data
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo run --release -- --input-file instances/test-case.txt --output-dir output

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: solver-ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update toolchain
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: rustup update
      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo build --release
      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: cargo test --release

